// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: proto/reverse/reverse.proto

package reverse

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReverseClient is the client API for Reverse service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReverseClient interface {
	CreateTask(ctx context.Context, in *ReqCreateTask, opts ...grpc.CallOption) (*RespCreateTask, error)
	ReportState(ctx context.Context, in *ReqReportState, opts ...grpc.CallOption) (*RespReportState, error)
}

type reverseClient struct {
	cc grpc.ClientConnInterface
}

func NewReverseClient(cc grpc.ClientConnInterface) ReverseClient {
	return &reverseClient{cc}
}

func (c *reverseClient) CreateTask(ctx context.Context, in *ReqCreateTask, opts ...grpc.CallOption) (*RespCreateTask, error) {
	out := new(RespCreateTask)
	err := c.cc.Invoke(ctx, "/reverse.Reverse/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reverseClient) ReportState(ctx context.Context, in *ReqReportState, opts ...grpc.CallOption) (*RespReportState, error) {
	out := new(RespReportState)
	err := c.cc.Invoke(ctx, "/reverse.Reverse/ReportState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReverseServer is the server API for Reverse service.
// All implementations must embed UnimplementedReverseServer
// for forward compatibility
type ReverseServer interface {
	CreateTask(context.Context, *ReqCreateTask) (*RespCreateTask, error)
	ReportState(context.Context, *ReqReportState) (*RespReportState, error)
	mustEmbedUnimplementedReverseServer()
}

// UnimplementedReverseServer must be embedded to have forward compatible implementations.
type UnimplementedReverseServer struct {
}

func (UnimplementedReverseServer) CreateTask(context.Context, *ReqCreateTask) (*RespCreateTask, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedReverseServer) ReportState(context.Context, *ReqReportState) (*RespReportState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportState not implemented")
}
func (UnimplementedReverseServer) mustEmbedUnimplementedReverseServer() {}

// UnsafeReverseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReverseServer will
// result in compilation errors.
type UnsafeReverseServer interface {
	mustEmbedUnimplementedReverseServer()
}

func RegisterReverseServer(s grpc.ServiceRegistrar, srv ReverseServer) {
	s.RegisterService(&Reverse_ServiceDesc, srv)
}

func _Reverse_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqCreateTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reverse.Reverse/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseServer).CreateTask(ctx, req.(*ReqCreateTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reverse_ReportState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqReportState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReverseServer).ReportState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reverse.Reverse/ReportState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReverseServer).ReportState(ctx, req.(*ReqReportState))
	}
	return interceptor(ctx, in, info, handler)
}

// Reverse_ServiceDesc is the grpc.ServiceDesc for Reverse service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reverse_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reverse.Reverse",
	HandlerType: (*ReverseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _Reverse_CreateTask_Handler,
		},
		{
			MethodName: "ReportState",
			Handler:    _Reverse_ReportState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/reverse/reverse.proto",
}
