// 版本声明，使用Protocol Buffers v3版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: proto/reverse/reverse.proto

// 默认包名

package reverse

import (
	common "github.com/wentaojin/microms/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任务创建
// 请求消息
type ReqCreateTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskUUID       string                 `protobuf:"bytes,1,opt,name=TaskUUID,proto3" json:"TaskUUID,omitempty"`
	TaskName       string                 `protobuf:"bytes,2,opt,name=TaskName,proto3" json:"TaskName,omitempty"`
	OracleDBEngine *common.OracleDBEngine `protobuf:"bytes,3,opt,name=OracleDBEngine,proto3" json:"OracleDBEngine,omitempty"`
	MySQLDBEngine  *common.MySQLDBEngine  `protobuf:"bytes,4,opt,name=MySQLDBEngine,proto3" json:"MySQLDBEngine,omitempty"`
	SQLiteDBEngine *common.SQLiteDBEngine `protobuf:"bytes,5,opt,name=SQLiteDBEngine,proto3" json:"SQLiteDBEngine,omitempty"`
}

func (x *ReqCreateTask) Reset() {
	*x = ReqCreateTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reverse_reverse_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqCreateTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCreateTask) ProtoMessage() {}

func (x *ReqCreateTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reverse_reverse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCreateTask.ProtoReflect.Descriptor instead.
func (*ReqCreateTask) Descriptor() ([]byte, []int) {
	return file_proto_reverse_reverse_proto_rawDescGZIP(), []int{0}
}

func (x *ReqCreateTask) GetTaskUUID() string {
	if x != nil {
		return x.TaskUUID
	}
	return ""
}

func (x *ReqCreateTask) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *ReqCreateTask) GetOracleDBEngine() *common.OracleDBEngine {
	if x != nil {
		return x.OracleDBEngine
	}
	return nil
}

func (x *ReqCreateTask) GetMySQLDBEngine() *common.MySQLDBEngine {
	if x != nil {
		return x.MySQLDBEngine
	}
	return nil
}

func (x *ReqCreateTask) GetSQLiteDBEngine() *common.SQLiteDBEngine {
	if x != nil {
		return x.SQLiteDBEngine
	}
	return nil
}

// 响应消息
type RespCreateTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskInfo *common.TaskInfo    `protobuf:"bytes,1,opt,name=TaskInfo,proto3" json:"TaskInfo,omitempty"`
	RespMsg  *common.ResponseMsg `protobuf:"bytes,2,opt,name=RespMsg,proto3" json:"RespMsg,omitempty"`
}

func (x *RespCreateTask) Reset() {
	*x = RespCreateTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reverse_reverse_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespCreateTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespCreateTask) ProtoMessage() {}

func (x *RespCreateTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reverse_reverse_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespCreateTask.ProtoReflect.Descriptor instead.
func (*RespCreateTask) Descriptor() ([]byte, []int) {
	return file_proto_reverse_reverse_proto_rawDescGZIP(), []int{1}
}

func (x *RespCreateTask) GetTaskInfo() *common.TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

func (x *RespCreateTask) GetRespMsg() *common.ResponseMsg {
	if x != nil {
		return x.RespMsg
	}
	return nil
}

// 任务进程
// 请求消息
type ReqReportState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskInfo *common.TaskInfo `protobuf:"bytes,1,opt,name=TaskInfo,proto3" json:"TaskInfo,omitempty"`
}

func (x *ReqReportState) Reset() {
	*x = ReqReportState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reverse_reverse_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqReportState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqReportState) ProtoMessage() {}

func (x *ReqReportState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reverse_reverse_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqReportState.ProtoReflect.Descriptor instead.
func (*ReqReportState) Descriptor() ([]byte, []int) {
	return file_proto_reverse_reverse_proto_rawDescGZIP(), []int{2}
}

func (x *ReqReportState) GetTaskInfo() *common.TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

// 响应消息
type RespReportState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskInfo       *common.TaskInfo `protobuf:"bytes,1,opt,name=TaskInfo,proto3" json:"TaskInfo,omitempty"`
	ReportStateMsg string           `protobuf:"bytes,2,opt,name=ReportStateMsg,proto3" json:"ReportStateMsg,omitempty"`
}

func (x *RespReportState) Reset() {
	*x = RespReportState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reverse_reverse_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespReportState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespReportState) ProtoMessage() {}

func (x *RespReportState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reverse_reverse_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespReportState.ProtoReflect.Descriptor instead.
func (*RespReportState) Descriptor() ([]byte, []int) {
	return file_proto_reverse_reverse_proto_rawDescGZIP(), []int{3}
}

func (x *RespReportState) GetTaskInfo() *common.TaskInfo {
	if x != nil {
		return x.TaskInfo
	}
	return nil
}

func (x *RespReportState) GetReportStateMsg() string {
	if x != nil {
		return x.ReportStateMsg
	}
	return ""
}

var File_proto_reverse_reverse_proto protoreflect.FileDescriptor

var file_proto_reverse_reverse_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2f,
	0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72,
	0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x1a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x84, 0x02, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x61, 0x73, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x55, 0x55, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x55, 0x55, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x0e, 0x4f,
	0x72, 0x61, 0x63, 0x6c, 0x65, 0x44, 0x42, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4f, 0x72, 0x61,
	0x63, 0x6c, 0x65, 0x44, 0x42, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x0e, 0x4f, 0x72, 0x61,
	0x63, 0x6c, 0x65, 0x44, 0x42, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x4d,
	0x79, 0x53, 0x51, 0x4c, 0x44, 0x42, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x79, 0x53, 0x51,
	0x4c, 0x44, 0x42, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x0d, 0x4d, 0x79, 0x53, 0x51, 0x4c,
	0x44, 0x42, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x3e, 0x0a, 0x0e, 0x53, 0x51, 0x4c, 0x69,
	0x74, 0x65, 0x44, 0x42, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x51, 0x4c, 0x69, 0x74, 0x65,
	0x44, 0x42, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x0e, 0x53, 0x51, 0x4c, 0x69, 0x74, 0x65,
	0x44, 0x42, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x22, 0x6d, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x2c, 0x0a, 0x08, 0x54, 0x61,
	0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08,
	0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2d, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x70,
	0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x52, 0x07,
	0x52, 0x65, 0x73, 0x70, 0x4d, 0x73, 0x67, 0x22, 0x3e, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x54, 0x61, 0x73,
	0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x54,
	0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x67, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x54, 0x61,
	0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08,
	0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67,
	0x32, 0x8e, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x16, 0x2e, 0x72, 0x65, 0x76,
	0x65, 0x72, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61,
	0x73, 0x6b, 0x1a, 0x17, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x22, 0x00, 0x12, 0x42, 0x0a,
	0x0b, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x72,
	0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x18, 0x2e, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22,
	0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x77, 0x65, 0x6e, 0x74, 0x61, 0x6f, 0x6a, 0x69, 0x6e, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x6d,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_reverse_reverse_proto_rawDescOnce sync.Once
	file_proto_reverse_reverse_proto_rawDescData = file_proto_reverse_reverse_proto_rawDesc
)

func file_proto_reverse_reverse_proto_rawDescGZIP() []byte {
	file_proto_reverse_reverse_proto_rawDescOnce.Do(func() {
		file_proto_reverse_reverse_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_reverse_reverse_proto_rawDescData)
	})
	return file_proto_reverse_reverse_proto_rawDescData
}

var file_proto_reverse_reverse_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_reverse_reverse_proto_goTypes = []interface{}{
	(*ReqCreateTask)(nil),         // 0: reverse.ReqCreateTask
	(*RespCreateTask)(nil),        // 1: reverse.RespCreateTask
	(*ReqReportState)(nil),        // 2: reverse.ReqReportState
	(*RespReportState)(nil),       // 3: reverse.RespReportState
	(*common.OracleDBEngine)(nil), // 4: common.OracleDBEngine
	(*common.MySQLDBEngine)(nil),  // 5: common.MySQLDBEngine
	(*common.SQLiteDBEngine)(nil), // 6: common.SQLiteDBEngine
	(*common.TaskInfo)(nil),       // 7: common.TaskInfo
	(*common.ResponseMsg)(nil),    // 8: common.ResponseMsg
}
var file_proto_reverse_reverse_proto_depIdxs = []int32{
	4, // 0: reverse.ReqCreateTask.OracleDBEngine:type_name -> common.OracleDBEngine
	5, // 1: reverse.ReqCreateTask.MySQLDBEngine:type_name -> common.MySQLDBEngine
	6, // 2: reverse.ReqCreateTask.SQLiteDBEngine:type_name -> common.SQLiteDBEngine
	7, // 3: reverse.RespCreateTask.TaskInfo:type_name -> common.TaskInfo
	8, // 4: reverse.RespCreateTask.RespMsg:type_name -> common.ResponseMsg
	7, // 5: reverse.ReqReportState.TaskInfo:type_name -> common.TaskInfo
	7, // 6: reverse.RespReportState.TaskInfo:type_name -> common.TaskInfo
	0, // 7: reverse.Reverse.CreateTask:input_type -> reverse.ReqCreateTask
	2, // 8: reverse.Reverse.ReportState:input_type -> reverse.ReqReportState
	1, // 9: reverse.Reverse.CreateTask:output_type -> reverse.RespCreateTask
	3, // 10: reverse.Reverse.ReportState:output_type -> reverse.RespReportState
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_reverse_reverse_proto_init() }
func file_proto_reverse_reverse_proto_init() {
	if File_proto_reverse_reverse_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_reverse_reverse_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqCreateTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reverse_reverse_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespCreateTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reverse_reverse_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqReportState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reverse_reverse_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespReportState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_reverse_reverse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reverse_reverse_proto_goTypes,
		DependencyIndexes: file_proto_reverse_reverse_proto_depIdxs,
		MessageInfos:      file_proto_reverse_reverse_proto_msgTypes,
	}.Build()
	File_proto_reverse_reverse_proto = out.File
	file_proto_reverse_reverse_proto_rawDesc = nil
	file_proto_reverse_reverse_proto_goTypes = nil
	file_proto_reverse_reverse_proto_depIdxs = nil
}
